### ISSUE TITLE
Colaboracion

### ISSUE THREAD

**Issue by Alejandro1Garcia** [Alejandro1Garcia/PercepcionN5E6#2]
Es tempranera como una campana.
Cabe en lo inverosímil, como un cuento
y cuando corta el hilo del momento
vierte su sangre blanca la mañana.

![image](https://user-images.githubusercontent.com/42418517/44594071-c78c8280-a78a-11e8-8a9e-adf246ee0f31.png)

Yo no sé rimar, pero lo intento
Es como si fuera algo malvado
Ya que siempre termino agotado
Aunque bueno, soy yo quien procesa lento

**Comment by Erick1211** [comment]
Edité el poema con esta estrofa:
Yo no sé rimar, pero lo intento
Es como si fuera algo malvado
Ya que siempre termino agotado
Aunque bueno, soy yo quien procesa lento

Chécala.

**Comment by Alejandro1Garcia** [comment]
Ok, Excelente ya quedo.
