### ISSUE TITLE
Tarea 3

### ISSUE THREAD

**Issue by Alejandro1Garcia** [Alejandro1Garcia/PercepcionN5E6#3]
Es tempranera como una campana.
Cabe en lo inverosímil, como un cuento
y cuando corta el hilo del momento
vierte su sangre blanca la mañana.

Ya no quiero rimar
Es muy tedioso
Es mucho de pensar
Y lo que escribo da oso

**Comment by MCarvajal96** [comment]
Deberías agregar los siguiente versos:
...
Si se viste de azul y va a la escuela 
no se distingue si camina o vuela, 
porque es como la brisa tan liviana 
![image](https://user-images.githubusercontent.com/42286020/44595125-c446c600-a78d-11e8-9132-6bbff6a6aee1.png)

**Comment by Erick1211** [comment]
Creo que con esta estrofa no se vería tan mal.

Ya no quiero rimar
Es muy tedioso
Es mucho de pensar
Y lo que escribo da oso

Chécala.

**Comment by Alejandro1Garcia** [comment]
Ok gracias por la colaboración
